resource_group_name = "TaskBoardRG"
resource_group_location = "West Europe"
app_service_plan_name = "TaskBoardSP"
app_service_name = "TaskBoardWA"
sql_server_name = "taskboardsql"
sql_database_name = "TaskBoardDB"
sql_admin_username = "sqladmin"